### PR TITLE
Update traking repo to point to Cosmic Core and Client changes

### PR DESCRIPTION
**Pull request by wilderrodrigues**

### CODE REVIEW

**Comment by miguelaferreira** [comment]
@wilderrodrigues is this still needed? I guess that the tacking repo has been updated already

**Comment by wilderrodrigues** [comment]
It is because the pom has changes as well. 1 line change, but that is still a change.

Cheers,
Wilder

Sent from my iPhone

On 15 Apr 2016, at 16:12, Miguel Ferreira <notifications@github.com<mailto:notifications@github.com>> wrote:

@wilderrodrigueshttps://github.com/wilderrodrigues is this still needed? I guess that the tacking repo has been updated already

**Comment by miguelaferreira** [comment]
can you separate that and leave the updating of submodules to the automatic job?
Edit: I can also do that if you agree it's ok

also the commits don't show that the pom changed, that's why I missed that change

and the second commit is only on1 module not 2.

**Comment by wilderrodrigues** [comment]
Yep, no problem.

Sent from my iPhone

On 15 Apr 2016, at 16:14, Miguel Ferreira <notifications@github.com<mailto:notifications@github.com>> wrote:

can you separate that and leave the updating of submodules to the automatic job?

**Comment by miguelaferreira** [comment]
Pushed  a new commit, can you check @wilderrodrigues?

**Comment by wilderrodrigues** [comment]
This change was already there, wasnt it? Why did you have to commit it and push?

**Comment by miguelaferreira** [comment]
It wasn't there. I took latest master and removed the line that your previous commits where removing...

**Comment by wilderrodrigues** [comment]
Commit ID c1e58caa4b76100e77fb53b247ae89fcb8695ca3 had his change. It just needed to be cleaned up - get rid of the tracking changes.

**Comment by wilderrodrigues** [comment]
Okay. Once the tests are done it can be merged along with the other PRs,

**Comment by miguelaferreira** [comment]
they are done. shall I merge?

Edit: it also needed to be rebased on current master. But if you really feel like having your commit back, go ahead

**Comment by wilderrodrigues** [comment]
No, the integration tests are not done yet. 

https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0020-tracking-repo-build/123/

**Pull request merged**
