### PR TITLE
First part of the Java 8 + Maven refactor

### PR DESCRIPTION
**Pull request by wilderrodrigues**
This PR removes the build source and test directories from the POM file, which are not following Maven conventions.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @michaelandersen @miguelaferreira @bheuvel 

I already did the following tests:
- Cleaned the Maven repository
- Built the source
- Generated and Installed RPMs
- Deployed DC
- Deployed VM on isolated network

Will now run some integration tests. Will keep you updated.

**Comment by miguelaferreira** [comment]
go build

**Comment by wilderrodrigues** [comment]
Ping @miguelaferreira @borisroman @michaelandersen @bheuvel 

Guys, tests results executed against the PRs related to Maven refactor:

Can we get this in? I would like to move to the next task.

```
[root@cs2 integration]# less /tmp//MarvinLogs/test_vm_life_cycle_FQ8NFX/results.txt 
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 18 tests in 4010.019s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_FQ8NFX/results.txt (END)
```

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
More tests:

```
[root@cs2 integration]# less /tmp//MarvinLogs/test_routers_iptables_default_policy_9NL79E/results.txt 
Check that the /etc/dhcphosts.txt doesn't contain duplicate IPs ... === TestName: test_router_dhcphosts | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policy on RouterVM ... === TestName: test_02_routervm_iptables_policies | Status : SUCCESS ===
ok
Test iptables default INPUT/FORWARD policies on VPC router ... === TestName: test_01_single_VPC_iptables_policies | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 3 tests in 2215.173s

OK
/tmp//MarvinLogs/test_routers_iptables_default_policy_9NL79E/results.txt (END)
```

**Comment by borisroman** [comment]
:+1:  LGTM

**Comment by borisroman** [comment]
go build

**Comment by wilderrodrigues** [comment]
Build in the bubble:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:27.407s
[INFO] Finished at: Mon Feb 08 19:14:15 GMT 2016
[INFO] Final Memory: 79M/371M
[INFO] ------------------------------------------------------------------------
[root@cs1 cosmic]#
```

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
Error on Jenkins:

image

**Comment by miguelaferreira** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Pull request merged**
