### PR TITLE
Adds XenServer maven module

### PR DESCRIPTION
**Pull request by wilderrodrigues**

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @bheuvel @remibergsma 

Tests:
- Source built successfully
- DB cleaned
- DC deployed (XenServer6.2)
- Deployed isolated network and VM

**Comment by wilderrodrigues** [comment]
Ping @bheuvel @borisroman 

This one as well. :)

**Comment by wilderrodrigues** [comment]
Ping @remibergsma @borisroman @bheuvel 

This one needs to be merged otherwise we will face conflicts later.
- Results of the integration tests:

```
[root@cs2 integration]# less /tmp//MarvinLogs/test_vm_life_cycle_HEHMOX/results.txt 
Test router internal advanced zone ... === TestName: test_02_router_internal_adv | Status : SUCCESS ===
ok
Test restart network ... === TestName: test_03_restart_network_cleanup | Status : SUCCESS ===
ok
Test router basic setup ... === TestName: test_05_router_basic | Status : SUCCESS ===
ok
Test router advanced setup ... === TestName: test_06_router_advanced | Status : SUCCESS ===
ok
Test stop router ... === TestName: test_07_stop_router | Status : SUCCESS ===
ok
Test start router ... === TestName: test_08_start_router | Status : SUCCESS ===
ok
Test reboot router ... === TestName: test_09_reboot_router | Status : SUCCESS ===
ok
Test reset virtual machine on reboot ... === TestName: test_01_reset_vm_on_reboot | Status : SUCCESS ===
ok
Test advanced zone virtual router ... === TestName: test_advZoneVirtualRouter | Status : SUCCESS ===
ok
Test Deploy Virtual Machine ... === TestName: test_deploy_vm | Status : SUCCESS ===
ok
Test Multiple Deploy Virtual Machine ... === TestName: test_deploy_vm_multiple | Status : SUCCESS ===
ok
Test Stop Virtual Machine ... === TestName: test_01_stop_vm | Status : SUCCESS ===
ok
Test Start Virtual Machine ... === TestName: test_02_start_vm | Status : SUCCESS ===
ok
Test Reboot Virtual Machine ... === TestName: test_03_reboot_vm | Status : SUCCESS ===
ok
Test destroy Virtual Machine ... === TestName: test_06_destroy_vm | Status : SUCCESS ===
ok
Test recover Virtual Machine ... === TestName: test_07_restore_vm | Status : SUCCESS ===
ok
Test migrate VM ... SKIP: At least two hosts should be present in the zone for migration
Test destroy(expunge) Virtual Machine ... === TestName: test_09_expunge_vm | Status : SUCCESS ===
ok

----------------------------------------------------------------------
Ran 18 tests in 1201.515s

OK (SKIP=1)
/tmp//MarvinLogs/test_vm_life_cycle_HEHMOX/results.txt (END)
```
- Executed Tests:

```
nosetests --with-marvin --marvin-config=/data/shared/marvin/mct-zone1-xen1-ISOLATED.cfg -s -a tags=advanced,required_hardware=false smoke/test_routers.py smoke/test_reset_vm_on_reboot.py smoke/test_vm_life_cycle.py
```

**Comment by bheuvel** [comment]
LGTM :+1:

**Pull request merged**
