### PR TITLE
Updated pom files to propagate groupId and version

### PR DESCRIPTION
**Pull request by borisroman**
groupId: cloud.cosmic
version: 5.0.0-SNAPSHOT

### CODE REVIEW

**Comment by borisroman** [comment]
Ping @wilderrodrigues @remibergsma @miguelaferreira

**Comment by wilderrodrigues** [comment]
Does it build? Because you adding a version to the checkstyle plugin that doesn't exist.

Do you want to change to this checkstyle already -> https://github.com/MissionCriticalCloud/checkstyle ?

Do they have a checkstyle project as a separate module as well? I'm a bit confused with this change. :)

Cheers,
Wilder

**Comment by borisroman** [comment]
Yeah it does! The "checkstyle" project is located in tools/checkstyle. - > It does have version number 5.0.0-SNAPSHOT.

It's a project inside cloudstack, not a plugin...

So, we don't have to change it to your actual checkstyle project right now

**Comment by wilderrodrigues** [comment]
Ah... now I got it. Basically they did the same thing we are doing now, except that our checkstyle project is separate so anyone can use it. :)

So, change LGTM :+1:  Merging...

Cheers,
Wilder

**Pull request merged**
