### PR TITLE
Adds packaging to git ignore file

### PR DESCRIPTION
**Pull request by wilderrodrigues**
We have to build the RPMs from the cosmic directory, that's why we clone it under cosmic and have it on gitignore to avoid problems.

### CODE REVIEW

**Comment by wilderrodrigues** [comment]
Ping @borisroman @remibergsma

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Pull request merged**
